# Generated by Django 4.2.23 on 2025-08-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_role_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
