# Generated by Django 4.2.23 on 2025-08-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_chapter_lesson_role_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
