# Generated by Django 4.2.23 on 2025-08-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_user_role'),
        ('courses', '0005_alter_course_category'),
    ]

    operations = [
    ]
