# Generated by Django 4.2.23 on 2025-08-27 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rolepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('enrolled', 'Đã đăng ký'), ('in_progress', 'Đang học'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='enrolled', max_length=20)),
                ('Payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='courses.payment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='usercourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercourse', to='courses.usercourse'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='user_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to='courses.usercourse'),
        ),
    ]
