# Generated by Django 4.2.23 on 2025-09-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_merge_0003_user_role_0005_alter_course_category'),
        ('courses', '0007_remove_course_thumbnail_url_remove_course_video_url_and_more'),
    ]

    operations = [
    ]
