# Generated by Django 4.2.23 on 2025-08-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ thanh toán'), ('IN_PROGRESS', 'Đang học'), ('FAILED', 'Không đạt yêu cầu'), ('COMPLETE', 'Hoàn thành'), ('INACTIVE', 'Bị khóa tài khoản')], default='PENDING', max_length=20),
        ),
    ]
