# Generated by Django 4.2.23 on 2025-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_usercourse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ thanh toán'), ('IN_PROGRESS', 'Đang học'), ('FAILED', 'Không đạt yêu cầu'), ('COMPLETE', 'Hoàn thành'), ('INACTIVE', 'Bị khóa tài khoản'), ('PAYMENT_FAILED', 'Thanh toán thất bại')], default='PENDING', max_length=20),
        ),
    ]
