# Generated by Django 4.2.23 on 2025-09-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_user_created_at_remove_user_role_and_more'),
        ('courses', '0009_usercourse_status'),
    ]

    operations = [
    ]
