# Generated by Django 4.2.23 on 2025-09-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_usercourse_status'),
    ]

    operations = [
         migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
