# Generated by Django 4.2.23 on 2025-09-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_user_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, default='', help_text="Lưu HTML cho phần 'Bạn sẽ học được gì' (ví dụ: <ul>...</ul>)", null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, default='', help_text="Lưu HTML cho phần 'Yêu cầu' (ví dụ: <ul>...</ul>)", null=True),
        ),
    ]