# Generated by Django 4.2.23 on 2025-09-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_topic_commenttopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learning_outcomes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='requirements',
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='Momo', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ thanh toán'), ('SUCCESS', 'Thanh toán thành công'), ('FAILED', 'Thanh toán thất bại')], default='PENDING', max_length=50),
        ),
        migrations.DeleteModel(
            name='CommentTopic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]