# Generated by Django 4.2.23 on 2025-09-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_topic_forum_remove_topic_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(default='', help_text='Learning outcomes in HTML format'),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(default='', help_text='Course requirements in HTML format'),
        ),
    ]