# Generated by Django 4.2.23 on 2025-09-21 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_learning_outcomes_course_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='completion_percentage',
            field=models.FloatField(default=0.0, help_text='Completion percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='last_watched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Chưa bắt đầu'), ('IN_PROGRESS', 'Đang học'), ('COMPLETED', 'Đã hoàn thành'), ('PAUSED', 'Tạm dừng')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='watch_time',
            field=models.IntegerField(default=0, help_text='Watch time in seconds'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('lesson', 'user')},
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_lessons', models.IntegerField(default=0)),
                ('completed_lessons', models.IntegerField(default=0)),
                ('total_watch_time', models.IntegerField(default=0, help_text='Total watch time in seconds')),
                ('completion_percentage', models.FloatField(default=0.0, help_text='Course completion percentage (0-100)')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course', 'user')},
            },
        ),
    ]