name: Deploy Production

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/course-be
            cd ~/Courses-Online-Api

            # Dừng tiến trình đang chiếm port 8080
            fuser -k 8080/tcp || true

            # Cập nhật code
            git fetch --all
            git reset --hard origin/main

            # Kích hoạt môi trường ảo
            source venv/bin/activate

            # Cài đặt lại dependencies
            pip install --upgrade pip
            pip install -r requirements.txt

            # Apply database migrations
            python manage.py makemigrations
            python manage.py migrate

            # Chạy lại server ở background
            nohup python manage.py runserver 0.0.0.0:8080 > server.log 2>&1 &
