name: Deploy Production

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create requirements file
        run: echo "${{secrets.REQUIREMENTS_PRODUCTION}}" | sed 's/^\xEF\xBB\xBF//' > requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/course-be
            cd ~/Courses-Online-Api
            git fetch --all
            git reset --hard origin/main
            echo "${{secrets.REQUIREMENTS_PRODUCTION}}" > requirements.txt
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py makemigrations
            python manage.py migrate
            python manage.py runserver 160.25.81.159:8080
