name: Deploy Production

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/course-be
            cd ~/Courses-Online-Api

            fuser -k 8080/tcp || true

            git fetch --all
            git reset --hard origin/main

            source venv/bin/activate

            python manage.py makemigrations
            python manage.py migrate

            # Chạy lại server ở background
            python manage.py runserver 160.25.81.159:8080
